"""Exact rotating-profile, compact completion, and simple-root oracle."""

import sympy as s

from substrate_framework.verification import CheckLedger


def main():
    checks = CheckLedger("P251-0123-actual-profile-moment-match")
    x, y, z = s.symbols("x y z", real=True)
    coords = (x, y, z)
    om, rho = s.symbols("Omega rho", positive=True)
    q1, q2 = s.symbols("q1 q2", real=True)
    j = s.Matrix([[0, -1], [1, 0]])
    q = s.Matrix([q1, q2])
    hprimitive = s.Function("H")(z)
    h = s.diff(hprimitive, z)
    g = s.Function("g")(x*x+y*y)
    u = s.Matrix([-om*y, om*x, 0])

    def xi(amplitude):
        return s.Matrix([g*h*amplitude[0], g*h*amplitude[1],
                         -(amplitude[0]*s.diff(g, x)+amplitude[1]*s.diff(g, y))*hprimitive])

    field = xi(q)
    checks.check("compact axial primitive completion is exactly divergence free",
                 s.simplify(sum(s.diff(field[i], coords[i]) for i in range(3))) == 0)
    potential = s.Matrix([q2*g*hprimitive, -q1*g*hprimitive, 0])
    curl_potential = s.Matrix([s.diff(potential[2], y)-s.diff(potential[1], z),
                              s.diff(potential[0], z)-s.diff(potential[2], x),
                              s.diff(potential[1], x)-s.diff(potential[0], y)])
    checks.check("the same field has an explicit compact vector potential",
                 (curl_potential-field).applyfunc(s.simplify) == s.zeros(3, 1))
    circulation = field.jacobian(coords)*u+field.jacobian(coords).T*u
    qdot = -om*j*q
    desired = xi(qdot)
    ja = j*q
    collar_source = s.Matrix([0, 0, (ja[0]*s.diff(g, x)+ja[1]*s.diff(g, y))*hprimitive])
    grad = s.Matrix([s.diff(u.dot(field), c) for c in coords])
    checks.check("actual Kelvin residual has the signed full pressure-completion source",
                 (-circulation-desired+2*om*collar_source+grad).applyfunc(s.simplify) == s.zeros(3, 1))
    checks.check("reversing the completion-source sign is exposed",
                 (-circulation-desired-2*om*collar_source+grad).applyfunc(s.simplify) != s.zeros(3, 1))
    column1, column2 = xi(s.Matrix([1, 0])), xi(s.Matrix([0, 1]))
    kks_density = rho*s.Matrix([0, 0, 2*om]).dot(column1.cross(column2))
    checks.check("complete KKS includes the exact vorticity factor two",
                 s.simplify(kks_density-2*rho*om*g*g*h*h) == 0)
    checks.check("omitting the axial completion would violate incompressibility",
                 s.simplify(q1*s.diff(g, x)*h+q2*s.diff(g, y)*h) != 0)

    # Material spin, including the term generated by the moving tag.
    r3 = s.Matrix(coords)
    core = s.Matrix([q1*h, q2*h, 0])
    core_dot = s.Matrix([qdot[0]*h, qdot[1]*h, 0])
    spin_density = rho*(r3.cross(core_dot)+2*core.cross(u))
    checks.check("actual transverse material spin equals z h times J qdot",
                 (spin_density[:2, :]-rho*z*h*j*qdot).applyfunc(s.simplify) == s.zeros(2, 1))
    checks.check("axial spin integrates to zero by transverse odd parity",
                 s.simplify(spin_density[2].subs({x: -x, y: -y})+spin_density[2]) == 0)
    moment_density = r3*core.T+core*r3.T
    checks.check("the nonzero shape cross moment accompanies the spin",
                 s.simplify(moment_density[0, 2]-q1*z*h) == 0
                 and s.simplify(moment_density[1, 2]-q2*z*h) == 0)

    beta, theta, rate, momentum = s.symbols("beta theta rate momentum", real=True)
    scalar_action = beta*momentum*rate-beta*om*(momentum**2+theta**2)/2
    reduced = s.expand(scalar_action.subs(momentum, rate/om))
    checks.check("physical scalar elimination derives beta over Omega inertia",
                 s.simplify(s.diff(reduced, rate, rate)-beta/om) == 0)

    # Independent exact profile integrals. These piecewise-polynomial C2
    # examples corroborate integrals only; the theorem uses smooth bumps
    # with the same strict inequalities, obtained by smooth approximation.
    v = s.Symbol("v", real=True)
    transition = 1-10*v**3+15*v**4-6*v**5
    checks.check("core transition and its first two derivatives meet both endpoints",
                 all(s.diff(transition, v, degree).subs(v, endpoint) == expected
                     for endpoint, expected_values in ((0, (1, 0, 0)), (1, (0, 0, 0)))
                     for degree, expected in enumerate(expected_values)))
    zz = 1+v/10
    a0 = 2*s.Rational(1, 3)+s.Rational(1, 5)*s.integrate(zz**2*transition**2, (v, 0, 1))
    b0 = 2*s.Rational(1, 3)+s.Rational(1, 5)*s.integrate(zz**2*transition, (v, 0, 1))
    checks.check("actual nearly-linear core integrals give the strict three-quarter margin",
                 a0 > 0 and b0 > 0 and a0/b0 > s.Rational(3, 4))
    phi = (v-1)**3*(2-v)**3
    a1 = 2*s.integrate(phi**2, (v, 1, 2))
    b1 = 2*s.integrate(v*phi, (v, 1, 2))
    checks.check("odd tail square and axial moment are positive exact integrals", a1 > 0 and b1 > 0)
    checks.check("tail profile has vanishing value and first two boundary derivatives",
                 all(s.diff(phi, v, degree).subs(v, endpoint) == 0
                     for endpoint in (1, 2) for degree in range(3)))

    c, d, aa1, bb1, constant = s.symbols("C D A1 B1 c0", positive=True)
    discriminant = d*d*bb1*bb1-8*c*aa1*constant
    root = 2*constant/(d*bb1+s.sqrt(discriminant))
    def polynomial(t):
        return 2*c*aa1*t*t-d*bb1*t+constant

    checks.check("stable small-root formula solves the derived moment quadratic",
                 s.simplify(polynomial(root)) == 0)
    checks.check("actual root derivative is negative square root of discriminant",
                 s.simplify(4*c*aa1*root-d*bb1+s.sqrt(discriminant)) == 0)
    checks.check("factor-two deletion does not solve the same measured moment equation",
                 s.simplify(c*aa1*root*root-d*bb1*root+constant) != 0)
    eps, scaled_tail = s.symbols("epsilon v_tail", positive=True)
    # epsilon=R^-3, t=epsilon*v_tail, A1=a1/epsilon, B1=b1/epsilon.
    scaled_equation = s.expand(polynomial(eps*scaled_tail).subs({aa1: a1/eps, bb1: b1/eps}))
    limiting_tail = constant/(d*b1)
    checks.check("large-separation limit derives finite physical tail moment",
                 s.simplify(scaled_equation.subs(eps, 0).subs(scaled_tail, limiting_tail)) == 0)
    checks.check("the same tail has vanishing squared norm of order R inverse cubed",
                 s.simplify((a1/eps)*(eps*limiting_tail)**2-eps*a1*constant**2/(d*d*b1*b1)) == 0)

    # Full pressure completion replaces LINEAR moments, not the KKS norm.
    a0s, b0s, t, e0, e1 = s.symbols("A0 B0 t pressure0 pressure1", real=True)
    complete = 2*c*(a0s+aa1*t*t)-d*(b0s+e0+t*(bb1+e1))
    checks.check("complete measured pressure row leaves the quadratic coefficient unchanged",
                 s.diff(complete, t, t) == 4*c*aa1)
    checks.check("the completed reference match is the actual angle-spin determinant",
                 s.simplify(s.Matrix([[0, -1], [rho*om*d*(b0s+e0+t*(bb1+e1)), 0]]).det()
                            -2*rho*om*c*(a0s+aa1*t*t)+rho*om*complete) == 0)

    kx, ky, kz = s.symbols("kx ky kz", real=True)
    wave = s.Matrix([kx, ky, kz])
    norm2 = wave.dot(wave)
    projector = s.eye(3)-wave*wave.T/norm2
    j3 = s.Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 0]])
    rotation_symbol = projector*j3*projector
    checks.check("full rotating-frame pressure symbol is skew on the solenoidal plane",
                 (rotation_symbol+rotation_symbol.T).applyfunc(s.simplify) == s.zeros(3))
    checks.check("the actual propagator has the smooth angular inertial-wave symbol",
                 (rotation_symbol**2+kz*kz*projector/norm2).applyfunc(s.simplify) == s.zeros(3))
    angle = s.Symbol("angle", real=True)
    def rot(x):
        return s.Matrix([[s.cos(x), -s.sin(x)], [s.sin(x), s.cos(x)]])

    checks.check("physical-vector rotation converts twice-Omega comoving motion to lab minus-Omega",
                 (rot(angle)*rot(-2*angle)-rot(-angle)).applyfunc(s.trigsimp) == s.zeros(2))
    print(f"Exact core A0={a0}, B0={b0}")
    print(f"Exact tail a1={a1}, b1={b1}")
    print("No floating-point eigenvalue, discriminant gate, or fitted frequency was evaluated.")
    return checks.finish()


if __name__ == "__main__":
    raise SystemExit(main())
