"""Exact tensor energy split and helical Galilean stationarity identities."""

import sympy as sp

from substrate_framework.verification import CheckLedger


def main():
    ledger = CheckLedger("P251-0039")
    q1, q2, q3 = sp.symbols("Q1 Q2 Q3", positive=True)
    second = sp.diag(q1, q2, q3)
    inertia = sp.trace(second)*sp.eye(3)-second
    a = sp.Matrix(3, 3, sp.symbols("a:9", real=True))
    # L_i=epsilon_ijk A_kl Q_jl is integrated r cross (A r), not copied spin.
    angular = sp.Matrix([
        sum(sp.LeviCivita(i, j, k)*a[k, ell]*second[j, ell]
            for j in range(3) for k in range(3) for ell in range(3))
        for i in range(3)
    ])
    omega = inertia.inv()*angular
    spin = sp.Matrix([[0, -omega[2], omega[1]], [omega[2], 0, -omega[0]],
                      [-omega[1], omega[0], 0]])
    residual = a-spin
    residual_angular = sp.Matrix([
        sum(sp.LeviCivita(i, j, k)*residual[k, ell]*second[j, ell]
            for j in range(3) for k in range(3) for ell in range(3))
        for i in range(3)
    ])
    ledger.check("locked residual has zero angular momentum",
                 sp.simplify(residual_angular) == sp.zeros(3, 1))
    total = sp.trace(a*second*a.T)/2
    split = (angular.T*inertia.inv()*angular)[0]/2
    split += sp.trace(residual*second*residual.T)/2
    ledger.check("full anisotropic kinetic tensor splits exactly",
                 sp.simplify(total-split) == 0)
    shear = a.subs({a[i, j]: (1 if (i, j) in ((0, 1), (1, 0)) else 0)
                   for i in range(3) for j in range(3)})
    shear_angular = angular.subs(dict(zip(a, shear)))
    ledger.check("anisotropic pure strain can carry angular momentum",
                 shear_angular == sp.Matrix([0, 0, q1-q2]))
    ledger.check("three-dimensional parcel inertia is strictly positive",
                 all(value.is_positive for value in inertia.diagonal()))

    # Screw-covariant vector generated by arbitrary functions on a cross-section.
    x, y, z = sp.symbols("x y z", real=True)
    h = sp.Symbol("h", positive=True)
    alpha, beta, rho = sp.symbols("alpha beta rho", real=True)
    angle = z/h
    rotation = sp.Matrix([[sp.cos(angle), -sp.sin(angle), 0],
                          [sp.sin(angle), sp.cos(angle), 0], [0, 0, 1]])
    xx = x*sp.cos(angle)+y*sp.sin(angle)
    yy = -x*sp.sin(angle)+y*sp.cos(angle)
    seed = sp.Matrix([sp.Function(f"v{i}")(xx, yy) for i in range(3)])
    v = rotation*seed
    j = sp.Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 0]])
    coords = (x, y, z)
    orbital = j*sp.Matrix(coords)
    screw_residual = j*v-v.jacobian(coords)*orbital-h*v.diff(z)
    ledger.check("general screw-covariance generator identity",
                 sp.simplify(screw_residual) == sp.zeros(3, 1))
    boost = sp.Matrix([0, 0, h*alpha+beta])
    profile_time_derivative = alpha*(j*v-v.jacobian(coords)*orbital)+beta*v.diff(z)
    ledger.check("rotation plus axial drift becomes pure axial traveling wave",
                 sp.simplify(profile_time_derivative-v.jacobian(coords)*boost) == sp.zeros(3, 1))
    rotating_acceleration = profile_time_derivative+v.jacobian(coords)*v
    stationary_acceleration = (v+boost).jacobian(coords)*(v+boost)
    ledger.check("boosted stationary Euler momentum residual is identical",
                 sp.simplify(stationary_acceleration-rotating_acceleration) == sp.zeros(3, 1))
    wrong_sign = (v-boost).jacobian(coords)*(v-boost)-rotating_acceleration
    ledger.check("opposite boost sign changes the equation",
                 sp.simplify(wrong_sign+2*(h*alpha+beta)*v.diff(z)) == sp.zeros(3, 1)
                 and wrong_sign != sp.zeros(3, 1))
    ledger.check("uniform axial boost leaves the vorticity unchanged",
                 boost.jacobian(coords) == sp.zeros(3, 3))
    print("Exact material/screw identities; no unresolved shape dynamics removed.")
    return int(ledger.finish())


if __name__ == "__main__":
    raise SystemExit(main())
